general {
    no_fade_in = false
    grab_cursor_events = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot   # Use 'screenshot' for real-time blur or provide a path to an image
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3     # 2-4 passes are good for performance/quality balance
    blur_size = 7       # Size of the blur
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <i>Choose the password, master...</i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}
label {
    monitor =
    text = $HYFETCH
    color = rgba(200, 200, 200, 1.0)
    font_size = 12
    font_family = monospace
    position = -400, 0   # push to the left
    halign = left
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 128
    font_family = SF Pro Display Bold
    position = 0, 150
    halign = center
    valign = center
}

image {
    monitor =
    path = /path/to/your/avatar.png # Path to your user icon
    size = 100
    border_size = 0
    position = 0, 50
    halign = center
    valign = center
}


